### PR TITLE
use lodash-es

### PR DESCRIPTION
**Pull request by pcvonz**
Uses `lodash-es` to enable tree shaking with webpack. 

✏️ Prettier ran on some of these files. Disable white space changes in the diff.

### CODE REVIEW

**Review by Morkos — CHANGES_REQUESTED** [review]
Overall, looks good. Do we need a major version update or is a minor update enough?

**Comment by pcvonz** [comment]
> Overall, looks good. Do we need a major version update or is a minor update enough?

There is no major update for `lodash`. `4.17.21` is the latest version.

**Comment by pcvonz** [comment]
> Overall, looks good. Do we need a major version update or is a minor update enough?

Oh, I just understood what you're asking. This can be a minor update since there aren't any breaking changes.

**Review by Morkos — APPROVED** [review]
Consider it approved once you update the version. You can use
```npm version minor```

**Pull request merged**
